CREATE SCHEMA IF NOT EXISTS Coma_Bem;
USE Coma_Bem;
CREATE TABLE IF NOT EXISTS Carrinho(
	idCarrinho INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NomeCliente VARCHAR(45) NOT NULL,
	ValorTotal DOUBLE NOT NULL,
	QtdProdutos INT NOT NULL
);
CREATE TABLE IF NOT EXISTS Produtos(
	idProdutos INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NomeProduto VARCHAR(45) NOT NULL,
	Valor DOUBLE NOT NULL,
	Quantidade INT NOT NULL,
	Carrinho_idCarrinho INT NOT NULL,
	CONSTRAINT fk_Produtos_Carrinho
		FOREIGN KEY (Carrinho_idCarrinho)
		REFERENCES Carrinho (idCarrinho)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);
ALTER TABLE Produtos
MODIFY COLUMN Quantidade VARCHAR(45) NOT NULL;